In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
vendas = pd.read_csv('vendas_supermercado_com_cliente.csv')
vendas.head()

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.60,49,2715.61
1,2023-01-01,Bananas,Alimentos Frescos,2.39,4,0.0,9.56,29,2280.15
2,2023-01-01,Laranjas,Alimentos Frescos,8.38,5,0.0,41.90,67,4419.56
3,2023-01-01,Tomates,Alimentos Frescos,2.03,15,0.0,30.45,29,3809.17
4,2023-01-01,Alface,Alimentos Frescos,37.14,14,0.0,519.96,24,1013.42

In [3]:
vendas.tail()

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
20070,2023-12-31,Produtos de higiene para pets,Pet Shop,26.62,15,0.21,315.4470,39,2475.82
20071,2023-12-31,Panelas,Utilidades Domésticas,33.00,19,0.15,532.9500,25,4766.49
20072,2023-12-31,Talheres,Utilidades Domésticas,27.60,12,0.29,235.1520,65,3367.68
20073,2023-12-31,Copos,Utilidades Domésticas,15.35,13,0.25,149.6625,42,3823.50
20074,2023-12-31,"Produtos descartáveis (pratos, copos, talheres)",Utilidades Domésticas,32.06,6,0.11,171.2004,59,3303.47

In [4]:
vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20075 entries, 0 to 20074
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         20075 non-null  object
 1   Produto      20075 non-null  object
 2   Categoria    20075 non-null  object
 3   Preço        20075 non-null  float64
 4   Quantidade   20075 non-null  int64
 5   Desconto     20075 non-null  float64
 6   Total_Venda  20075 non-null  float64
 7   Idade        20075 non-null  int64
 8   Renda        20075 non-null  float64
dtypes: float64(4), int64(2), object(3)
memory usage: 1.4+ MB

In [5]:
vendas.describe(include='all')

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
count,20075,20075,20075,20075.000000,20075.000000,20075.000000,20075.000000,20075.000000,20075.000000
unique,365,55,9,NaN,NaN,NaN,NaN,NaN,NaN
top,2023-01-01,Maçãs,Alimentos Frescos,NaN,NaN,NaN,NaN,NaN,NaN
freq,55,365,5475,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,25.577109,10.007671,0.039760,245.901736,45.992827,2999.034265
std,NaN,NaN,NaN,14.115988,5.488450,0.085011,207.773694,16.482103,1159.717376
min,NaN,NaN,NaN,1.000000,1.000000,0.000000,0.910200,18.000000,1000.380000
25%,NaN,NaN,NaN,13.260000,5.000000,0.000000,75.604500,32.000000,1993.625000
50%,NaN,NaN,NaN,25.660000,10.000000,0.000000,186.320000,46.000000,2998.830000
75%,NaN,NaN,NaN,37.770000,15.000000,0.000000,370.040000,60.000000,4007.675000
max,NaN,NaN,NaN,49.990000,19.000000,0.500000,949.050000,74.000000,4999.760000